services:
  traefik:
    image: "traefik:3.6"
    command:
      #  - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
    - "80:80"
    - "443:443"
    networks:
    - k-network
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.6
    networks:
    - k-network
    ports:
    - 18080:8080
    volumes: 
    - ./conf/keycloak:/opt/keycloak/data/import:z
    command:
      - start
      - --import-realm
      #- --optimized
      #- --auto-build
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /auth/health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - traefik.enable=true
      # Service definition (shared by both routers)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
      # HTTP router (no redirect - for testing)
      - traefik.http.routers.keycloak-web.rule=PathPrefix(`/auth`)
      - traefik.http.routers.keycloak-web.entrypoints=web
      - traefik.http.routers.keycloak-web.service=keycloak
      # HTTPS router
      - traefik.http.routers.keycloak-websecure.rule=PathPrefix(`/auth`)
      - traefik.http.routers.keycloak-websecure.entrypoints=websecure
      - traefik.http.routers.keycloak-websecure.tls=true
      - traefik.http.routers.keycloak-websecure.service=keycloak
    environment:
      # https://www.keycloak.org/server/reverseproxy
      # https://www.keycloak.org/server/hostname
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      # Proxy settings (v2) - replaces deprecated KC_PROXY
      KC_PROXY_HEADERS: "xforwarded"
      # Hostname settings (v2) - replaces deprecated hostname-strict options
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_DEBUG: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      # https://www.keycloak.org/server/features
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
  postgres:
    image: postgres:18-alpine
    networks:
    - k-network
    environment:
      POSTGRES_PASSWORD: password
      #PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
    - ./conf/postgres/keycloak-init.sh:/docker-entrypoint-initdb.d/keycloak-init.sh
    #- ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  k-network:
